### ISSUE TITLE
Skipped push of article ##### to Apple News because it is already in sync.

### ISSUE THREAD

**Issue by alexbrothman** [alleyinteractive/apple-news#1125]
### Description of the bug

I have several articles with a **Sync Status** of _Needs to be updated_. When I click **Pubish** I see an error that says _Skipped push of article ##### to Apple News because it is already in sync._.

Additionally, when I attempt to delete an article from Apple News using the plugin, I receive a message that the article has been deleted but it is not actually removed from Apple News. I manually deleted a published article from Apple News and attempted re-publish it, though I received the same _Skipped push of article ##### to Apple News because it is already in sync._ message.

![Uploading Screenshot 2024-05-17 at 11.09.58.png…]()

### Steps To Reproduce

1. From, /wp-admin/admin.php?page=apple_news_index, identify an article with a **Sync Status** of _Needs to be updated_.
2. Click **Publish** on the article that needs to be updated.

**Comment by timatron** [comment]
We're seeing this problem pretty often. To reproduce:

1. publish an article
2. backdate the article and update it

Article never makes it to apple news and has this same issue. 

@kevinfodness can this be solved by having articles only published on an hourly cronjob?

**Comment by kevinfodness** [comment]
No, it's an issue with how we're calculating what constitutes a change to the article. It's a subset of fields (title, post content, a few others). This functionality is in need of overhaul so that we regenerate the JSON and compare it to a prior hash rather than checking individual fields (e.g., a post itself may not have changed at all, but a change to the theme would necessitate an update to the article in order to capture the updated theme value).

**Comment by julesyoungberg** [comment]
I am getting this after attempting to delete an article from apple news so that we could republish it. The reason for doing so was that it was not appearing in our feed even though it was accessible by link. Looked like the meta was not properly deleted, but after deleting it manually I still get the same error 😕

**Comment by timatron** [comment]
We have the same issue here @julesyoungberg

**Comment by mogmarsh** [comment]
@kevinfodness I wonder if a good first step would be to add a checkbox for "Force Update" that would just skip this comparison if checked. This would allow users to force an update for any reason they felt necessary, and could be followed up later with the JSON hash comparison.
